<?php
define('ERREUR_EMAIL', 1);
define('ERREUR_PASSWORD_LENGTH', 2);
define('ERREUR_PASSWORD_IDENTIQUE', 3);
define('ERREUR_CHAMP_VIDE', 4);
define('ERREUR_ENREGISTREMENT', 5);
define('ERREUR_CONNEXION', 6);
